layout_spectrum: 0.7831541
name: Kuku Mama
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.109319
color:
  brandStrength: 1
  lightness: 0.8085107
  saturation: 0.2638298
  rhythmicContrast: 0.02778557
  brandColors:
    - '#00AA9D'
    - '#000101'
    - '#001513'
    - '#004F49'
    - '#008379'
